<a href="https://colab.research.google.com/github/vincnardelli/covstat/blob/master/covstat_vaccini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Confronto Italia - Germania

In [2]:
vaccinations = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv")

In [14]:
stati = ["Germany", "Italy"]
df = vaccinations[vaccinations.location.isin(stati)]
df = df.pivot(index='date', columns='location', values=['total_vaccinations', 'total_vaccinations_per_hundred'])
df.columns = df.columns.map('_'.join).str.strip('')
df.reset_index(inplace=True)
df.date = pd.to_datetime(df.date).dt.strftime('%d-%m-%Y')
df['spread'] = df['total_vaccinations_per_hundred_Germany'] - df['total_vaccinations_per_hundred_Italy']
df.dropna(axis=0, inplace = True)
df['total_vaccinations_Germany'] = df['total_vaccinations_Germany'].astype(int)
df['total_vaccinations_Italy'] = df['total_vaccinations_Italy'].astype(int)
df['spread'] = round(df['spread'], 2)
spread = df.tail(1)
spread['spread'] = spread['spread']*100
spread['spread'] = spread['spread'].astype(int)
spread.to_csv("confronto_italia_germania_last.csv")

In [ ]:
df = vaccinations[vaccinations.location.isin(stati)]
df.drop(columns=['iso_code', 'total_vaccinations', 'daily_vaccinations', 'daily_vaccinations_per_million', 
                 'people_fully_vaccinated', 'daily_vaccinations_raw', 'people_vaccinated', 'people_vaccinated_per_hundred', 
                 'people_fully_vaccinated_per_hundred'], inplace=True)
df = df.melt(id_vars = ['location', 'date'])
df.reset_index(inplace=True)
df.date = pd.to_datetime(df.date).dt.strftime('%d-%m-%Y')
df.to_csv("confronto_italia_germania.csv")
df

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

    index location        date                        variable  value
0       0  Germany  27-12-2020  total_vaccinations_per_hundred   0.03
1       1  Germany  28-12-2020  total_vaccinations_per_hundred   0.05
2       2  Germany  29-12-2020  total_vaccinations_per_hundred   0.10
3       3  Germany  30-12-2020  total_vaccinations_per_hundred   0.17
4       4  Germany  31-12-2020  total_vaccinations_per_hundred   0.21
5       5  Germany  01-01-2021  total_vaccinations_per_hundred   0.25
6       6  Germany  02-01-2021  total_vaccinations_per_hundred   0.30
7       7  Germany  03-01-2021  total_vaccinations_per_hundred   0.33
8       8  Germany  04-01-2021  total_vaccinations_per_hundred   0.39
9       9  Germany  05-01-2021  total_vaccinations_per_hundred   0.45
10     10  Germany  06-01-2021  total_vaccinations_per_hundred   0.51
11     11  Germany  07-01-2021  total_vaccinations_per_hundred   0.58
12     12  Germany  08-01-2021  total_vaccinations_per_hundred   0.65
13     13  Germany  09-01-2021  total_vaccinations_per_hundred   0.71
14     14  Germany  10-01-2021  total_vaccinations_per_hundred   0.75
15     15  Germany  11-01-2021  total_vaccinations_per_hundred   0.82
16     16    Italy  27-12-2020  total_vaccinations_per_hundred   0.01
17     17    Italy  28-12-2020  total_vaccinations_per_hundred   0.01
18     18    Italy  29-12-2020  total_vaccinations_per_hundred   0.02
19     19    Italy  30-12-2020  total_vaccinations_per_hundred   0.02
20     20    Italy  31-12-2020  total_vaccinations_per_hundred   0.06
21     21    Italy  01-01-2021  total_vaccinations_per_hundred   0.08
22     22    Italy  02-01-2021  total_vaccinations_per_hundred   0.15
23     23    Italy  03-01-2021  total_vaccinations_per_hundred   0.20
24     24    Italy  04-01-2021  total_vaccinations_per_hundred   0.31
25     25    Italy  05-01-2021  total_vaccinations_per_hundred   0.44
26     26    Italy  06-01-2021  total_vaccinations_per_hundred   0.55
27     27    Italy  07-01-2021  total_vaccinations_per_hundred   0.70
28     28    Italy  08-01-2021  total_vaccinations_per_hundred   0.85
29     29    Italy  09-01-2021  total_vaccinations_per_hundred   0.99
30     30    Italy  10-01-2021  total_vaccinations_per_hundred   1.08
31     31    Italy  11-01-2021  total_vaccinations_per_hundred   1.21
32     32    Italy  12-01-2021  total_vaccinations_per_hundred   1.32

## Confronto internazionale

In [ ]:
stati = ['Italy', 'Germany', 'United Kingdom', 'Spain', 'United States']
df = vaccinations[vaccinations.location.isin(stati)]
df.drop(columns=['iso_code',
                 'people_fully_vaccinated', 'daily_vaccinations_raw', 'people_vaccinated', 'people_vaccinated_per_hundred', 
                 'people_fully_vaccinated_per_hundred'], inplace=True)
df = df.melt(id_vars = ['location', 'date'])
df = df.pivot(index = ['date', 'variable'], columns = 'location', values= 'value')
df.reset_index(inplace=True)
df.date = pd.to_datetime(df.date).dt.strftime('%d-%m-%Y')
df.loc[df['variable'] == 'daily_vaccinations', ['variable']] = "Vaccinazioni giornaliere"
df.loc[df['variable'] == 'daily_vaccinations_per_million', ['variable']] = "Vaccinazioni giornaliere ogni milione ab"
df.loc[df['variable'] == 'total_vaccinations', ['variable']] = "Totale vaccinazioni"
df.loc[df['variable'] == 'total_vaccinations_per_hundred', ['variable']] = "Totale vaccinazioni ogni cento abitanti"

df.to_csv("confronto_stati.csv")
df

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

location        date  ... United States
0         20-12-2020  ...           NaN
1         20-12-2020  ...           NaN
2         20-12-2020  ...     556208.00
3         20-12-2020  ...          0.17
4         21-12-2020  ...      57909.00
..               ...  ...           ...
91        11-01-2021  ...          2.72
92        12-01-2021  ...     641524.00
93        12-01-2021  ...       1938.00
94        12-01-2021  ...    9327138.00
95        12-01-2021  ...          2.82

[96 rows x 7 columns]

## Analisi vaccini Italia

In [ ]:
anagrafica = pd.read_csv("https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.csv")
dati_istat = pd.read_csv("https://raw.githubusercontent.com/vincnardelli/covstat/master/vaccini/dati_istat.csv", sep=";")
dati_istat

  fascia_anagrafica  pop_maschile  pop_femminile
0             20-29       3192324        2964859
1             30-39       3500589        3452131
2             40-49       4495422        4544377
3             50-59       4656253        4844927
4             60-69       3554434        3870741
5             70-79       2753864        3252966
6             80-89       1446283        2201193
7               90+        217463         577109

In [ ]:
anagrafica = anagrafica.merge(dati_istat, on="fascia_anagrafica")
anagrafica['Maschi'] = anagrafica['sesso_maschile']/anagrafica['pop_maschile']
anagrafica['Femmine'] = anagrafica['sesso_femminile']/anagrafica['pop_femminile']

In [ ]:
anagrafica_graph = anagrafica[['fascia_anagrafica','Maschi', 'Femmine']]
anagrafica_graph.set_index('fascia_anagrafica', inplace = True)
anagrafica_graph['Femmine'] = anagrafica_graph['Femmine']*-100
anagrafica_graph['Maschi'] = anagrafica_graph['Maschi']*100
anagrafica_graph = round(anagrafica_graph, 2)
anagrafica_graph.to_csv("italia_anagrafica.csv")
anagrafica_graph

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

                   Maschi  Femmine
fascia_anagrafica
20-29                0.93    -1.92
30-39                1.48    -2.29
40-49                1.22    -2.51
50-59                1.61    -3.04
60-69                1.93    -1.49
70-79                0.46    -0.24
80-89                0.49    -0.82
90+                  1.32    -2.77

## Regioni italiane

In [ ]:
popolation_regions = np.array([ 1304970,      559084,        533050,   1947131,   5801692,         
                               4459477,        1215220,5879082, 1550640,    
                               10060574,  1525271,  305617,    4356406, 4029053, 1639591,  
                               4999891,  3729641,       541380,  882015,          125666, 4905854])
name_regions       = np.array(['Abruzzo','Basilicata','P.A. Bolzano','Calabria','Campania',
                               'Emilia-Romagna','Friuli Venezia Giulia','Lazio','Liguria',
                               'Lombardia','Marche','Molise','Piemonte','Puglia','Sardegna',
                               'Sicilia','Toscana','P.A. Trento','Umbria','Valle d\'Aosta','Veneto'])
area       = np.array(['ABR','BAS','PAB','CAL','CAM',
                               'EMR','FVG','LAZ','LIG',
                               'LOM','MAR','MOL','PIE','PUG','SAR',
                               'SIC','TOS','PAT','UMB','VDA','VEN'])

popolation = pd.DataFrame([name_regions, popolation_regions, area]).transpose()
popolation.columns = ['regione', 'popolazione', 'area']

In [ ]:
regioni = pd.read_csv("https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-summary-latest.csv")
regioni = regioni.merge(popolation, on='area')

regioni['Totale vaccinazioni'] = regioni.groupby(['regione'])['totale'].apply(lambda x: x.cumsum())
regioni['Totale vaccinazioni ogni cento ab'] = regioni['Totale vaccinazioni']/regioni['popolazione']*100
regioni['Totale vaccinazioni ogni cento ab'] = round(regioni['Totale vaccinazioni ogni cento ab'].astype(float), 2)


regioni['Vaccinazioni giornaliere ogni cento ab'] = regioni['totale']/regioni['popolazione']*100
regioni['Vaccinazioni giornaliere ogni cento ab'] = round(regioni['Vaccinazioni giornaliere ogni cento ab'].astype(float), 2)

regioni = regioni.rename(columns={'data_somministrazione': 'data', 
                        'totale': 'Vaccinazioni giornaliere', 
                        'categoria_operatori_sanitari_sociosanitari': 'Operatori sanitari - sociosanitari', 
                        'categoria_personale_non_sanitario': 'Personale non sanitario', 
                        'categoria_ospiti_rsa': 'Ospiti RSA', 
                        'regione': 'Regione'})
#regioni.reset_index(inplace=True)
#regioni.data = pd.to_datetime(regioni.data).dt.strftime('%d-%m-%Y')
regioni.to_csv("regioni.csv")

In [ ]:
confronto_regioni = regioni[['data', 'Regione', 'Totale vaccinazioni', 'Totale vaccinazioni ogni cento ab', 'Vaccinazioni giornaliere', 'Vaccinazioni giornaliere ogni cento ab']]
confronto_regioni = confronto_regioni.melt(id_vars = ['Regione', 'data'])
confronto_regioni = confronto_regioni.pivot(index = ['data', 'variable'], columns = 'Regione', values= 'value')
confronto_regioni.reset_index(inplace=True)
confronto_regioni.data = pd.to_datetime(confronto_regioni.data).dt.strftime('%m-%d-%Y')
confronto_regioni.to_csv("confronto_regioni.csv")

In [ ]:
confronto_regioni

Regione        data  ...    Veneto
0        12-27-2020  ...    880.00
1        12-27-2020  ...      0.02
2        12-27-2020  ...    880.00
3        12-27-2020  ...      0.02
4        12-28-2020  ...       NaN
..              ...  ...       ...
63       01-11-2021  ...      0.13
64       01-12-2021  ...  80440.00
65       01-12-2021  ...      1.64
66       01-12-2021  ...   4694.00
67       01-12-2021  ...      0.10

[68 rows x 23 columns]

# Piano vaccinale

In [ ]:
dfIT = vaccinations[vaccinations['location']=='Italy'].iloc[2:,:]
dati_ITALIA = np.array(dfIT.iloc[3:,3])/(10**6)
x_ITALIA = np.arange(0,len(dati_ITALIA))/7

# requisiti per scenario minimo e immunità di gregge

over65 = 14*10**6
operatori_sanitari = 6.5*10**5
periodo = 30*9
soglia_immunita = 70/100
n_dosi = 2
popolazione = 60*10**6
obj_minimo = (over65+operatori_sanitari)*2
obj_ideale = (70/100*60*10**6)*2
minimo_daily = n_dosi*(over65+operatori_sanitari)/periodo
immunità_daily = n_dosi*(soglia_immunita*popolazione)/periodo

dfIT_soglie = dfIT[['date','total_vaccinations']]
dfIT_soglie = dfIT_soglie.iloc[2:,:]
dfIT_soglie.iloc[6,1] = 321077
ll = len(dfIT_soglie)
 
dfIT_soglie['minimo'] = minimo_daily*np.arange(1,ll+1)
dfIT_soglie['immunità'] = immunità_daily*np.arange(1,ll+1)
 
dfIT_soglie['daily'] = np.diff(np.append(14613,np.array(dfIT_soglie['total_vaccinations'])))
days = np.arange(270,0,-1)[0:len(dfIT_soglie)]

dfIT_soglie['nane_min']=(obj_minimo-np.array(dfIT_soglie['total_vaccinations']))/days
dfIT_soglie['nane_ideal']=(obj_ideale-np.array(dfIT_soglie['total_vaccinations']))/days




print(minimo_daily)
print(immunità_daily)

n_week = 3/4*52

week_min = obj_minimo/n_week/10**6
week_ideal = obj_ideale/n_week/10**6

week_grid = np.arange(0,n_week+0.1)

108518.51851851853
311111.1111111111

In [ ]:
# piano vaccini
week_vaccini = [0,13,26,39,52,65,78]

piano_vaccini_diff = np.array([0,28.269*10**6,57.202*10**6,53.84*10**6,
                 14.806*10**6,28.266*10**6,20.19*10**6])/10**6

piano_vaccini = np.cumsum(piano_vaccini_diff)

In [ ]:
pianovaccini = pd.DataFrame({"week": week_vaccini, "Numero di dosi piano vaccini": piano_vaccini})
pianovaccini

   week  Numero di dosi piano vaccini
0     0                         0.000
1    13                        28.269
2    26                        85.471
3    39                       139.311
4    52                       154.117
5    65                       182.383
6    78                       202.573

In [ ]:
vaccinazioni = pd.DataFrame({"week":x_ITALIA, "Vaccini effettuati": dati_ITALIA})
vaccinazioni

        week  Vaccini effettuati
0   0.000000            0.049410
1   0.142857            0.087833
2   0.285714            0.122510
3   0.428571            0.190144
4   0.571429            0.268319
5   0.714286            0.332247
6   0.857143            0.422492
7   1.000000            0.512868
8   1.142857            0.597017
9   1.285714            0.655941
10  1.428571            0.730453
11  1.571429            0.800730

In [ ]:
projection = pd.DataFrame({"week": week_grid, 
                          "70% di vaccinati entro 30/09/21": week_grid*week_ideal, 
                           "Over 65 e op.sanitari vaccinati entro 30/09/21": week_grid*week_min})
projection

    week  ...  Over 65 e op.sanitari vaccinati entro 30/09/21
0    0.0  ...                                        0.000000
1    1.0  ...                                        0.751282
2    2.0  ...                                        1.502564
3    3.0  ...                                        2.253846
4    4.0  ...                                        3.005128
5    5.0  ...                                        3.756410
6    6.0  ...                                        4.507692
7    7.0  ...                                        5.258974
8    8.0  ...                                        6.010256
9    9.0  ...                                        6.761538
10  10.0  ...                                        7.512821
11  11.0  ...                                        8.264103
12  12.0  ...                                        9.015385
13  13.0  ...                                        9.766667
14  14.0  ...                                       10.517949
15  15.0  ...                                       11.269231
16  16.0  ...                                       12.020513
17  17.0  ...                                       12.771795
18  18.0  ...                                       13.523077
19  19.0  ...                                       14.274359
20  20.0  ...                                       15.025641
21  21.0  ...                                       15.776923
22  22.0  ...                                       16.528205
23  23.0  ...                                       17.279487
24  24.0  ...                                       18.030769
25  25.0  ...                                       18.782051
26  26.0  ...                                       19.533333
27  27.0  ...                                       20.284615
28  28.0  ...                                       21.035897
29  29.0  ...                                       21.787179
30  30.0  ...                                       22.538462
31  31.0  ...                                       23.289744
32  32.0  ...                                       24.041026
33  33.0  ...                                       24.792308
34  34.0  ...                                       25.543590
35  35.0  ...                                       26.294872
36  36.0  ...                                       27.046154
37  37.0  ...                                       27.797436
38  38.0  ...                                       28.548718
39  39.0  ...                                       29.300000

[40 rows x 3 columns]

In [ ]:
projection = projection.merge(pianovaccini, how="left")
projection = projection.merge(vaccinazioni, how="left")
projection.to_csv("projection.csv")
projection

    week  ...  Vaccini effettuati
0    0.0  ...            0.049410
1    1.0  ...            0.512868
2    2.0  ...                 NaN
3    3.0  ...                 NaN
4    4.0  ...                 NaN
5    5.0  ...                 NaN
6    6.0  ...                 NaN
7    7.0  ...                 NaN
8    8.0  ...                 NaN
9    9.0  ...                 NaN
10  10.0  ...                 NaN
11  11.0  ...                 NaN
12  12.0  ...                 NaN
13  13.0  ...                 NaN
14  14.0  ...                 NaN
15  15.0  ...                 NaN
16  16.0  ...                 NaN
17  17.0  ...                 NaN
18  18.0  ...                 NaN
19  19.0  ...                 NaN
20  20.0  ...                 NaN
21  21.0  ...                 NaN
22  22.0  ...                 NaN
23  23.0  ...                 NaN
24  24.0  ...                 NaN
25  25.0  ...                 NaN
26  26.0  ...                 NaN
27  27.0  ...                 NaN
28  28.0  ...                 NaN
29  29.0  ...                 NaN
30  30.0  ...                 NaN
31  31.0  ...                 NaN
32  32.0  ...                 NaN
33  33.0  ...                 NaN
34  34.0  ...                 NaN
35  35.0  ...                 NaN
36  36.0  ...                 NaN
37  37.0  ...                 NaN
38  38.0  ...                 NaN
39  39.0  ...                 NaN

[40 rows x 5 columns]

In [ ]:
vaccinazioni = pd.DataFrame({"week":x_ITALIA, "Vaccini effettuati": dati_ITALIA, 
                                                       "70% di vaccinati entro 30/09/21": x_ITALIA*week_ideal,
                             "Over 65 e op.sanitari vaccinati entro 30/09/21": x_ITALIA*week_min 
})
vaccinazioni.to_csv("projection_vaccinazioni.csv")