<a href="https://colab.research.google.com/github/vincnardelli/covstat/blob/master/covstat_vaccini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Confronto Italia - Germania

In [ ]:
vaccinations = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv")

In [ ]:
stati = ["Germany", "Italy"]
df = vaccinations[vaccinations.location.isin(stati)]
df = df.pivot(index='date', columns='location', values=['total_vaccinations', 'total_vaccinations_per_hundred'])
df.columns = df.columns.map('_'.join).str.strip('')
df.reset_index(inplace=True)
df.date = pd.to_datetime(df.date).dt.strftime('%d-%m-%Y')
df['spread'] = df['total_vaccinations_per_hundred_Germany'] - df['total_vaccinations_per_hundred_Italy']
df.dropna(axis=0, inplace = True)
df['total_vaccinations_Germany'] = df['total_vaccinations_Germany'].astype(int)
df['total_vaccinations_Italy'] = df['total_vaccinations_Italy'].astype(int)
df['spread'] = round(df['spread'], 2)
df.tail(1).to_csv("confronto_italia_germania_last.csv")

          date  ...  spread
11  07-01-2021  ...   -0.11

[1 rows x 6 columns]

In [ ]:
df = vaccinations[vaccinations.location.isin(stati)]
df.drop(columns=['iso_code', 'total_vaccinations', 'daily_vaccinations', 'daily_vaccinations_per_million'], inplace=True)
df = df.melt(id_vars = ['location', 'date'])
df.reset_index(inplace=True)
df.date = pd.to_datetime(df.date).dt.strftime('%d-%m-%Y')
df.to_csv("confronto_italia_germania.csv")
df

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

    index location        date                        variable  value
0       0  Germany  27-12-2020  total_vaccinations_per_hundred   0.03
1       1  Germany  28-12-2020  total_vaccinations_per_hundred   0.05
2       2  Germany  29-12-2020  total_vaccinations_per_hundred   0.10
3       3  Germany  30-12-2020  total_vaccinations_per_hundred   0.17
4       4  Germany  31-12-2020  total_vaccinations_per_hundred   0.21
5       5  Germany  01-01-2021  total_vaccinations_per_hundred   0.25
6       6  Germany  02-01-2021  total_vaccinations_per_hundred   0.30
7       7  Germany  03-01-2021  total_vaccinations_per_hundred   0.33
8       8  Germany  04-01-2021  total_vaccinations_per_hundred   0.39
9       9  Germany  05-01-2021  total_vaccinations_per_hundred   0.45
10     10  Germany  06-01-2021  total_vaccinations_per_hundred   0.51
11     11  Germany  07-01-2021  total_vaccinations_per_hundred   0.57
12     12    Italy  27-12-2020  total_vaccinations_per_hundred   0.01
13     13    Italy  28-12-2020  total_vaccinations_per_hundred   0.01
14     14    Italy  29-12-2020  total_vaccinations_per_hundred   0.02
15     15    Italy  30-12-2020  total_vaccinations_per_hundred   0.02
16     16    Italy  31-12-2020  total_vaccinations_per_hundred   0.06
17     17    Italy  01-01-2021  total_vaccinations_per_hundred   0.08
18     18    Italy  02-01-2021  total_vaccinations_per_hundred   0.14
19     19    Italy  03-01-2021  total_vaccinations_per_hundred   0.20
20     20    Italy  04-01-2021  total_vaccinations_per_hundred   0.31
21     21    Italy  05-01-2021  total_vaccinations_per_hundred   0.44
22     22    Italy  06-01-2021  total_vaccinations_per_hundred   0.54
23     23    Italy  07-01-2021  total_vaccinations_per_hundred   0.68

## Confronto internazionale

In [ ]:
stati = ['Italy', 'Germany', 'United Kingdom', 'Spain', 'United States']
df = vaccinations[vaccinations.location.isin(stati)]
df.drop(columns=['iso_code'], inplace=True)
df = df.melt(id_vars = ['location', 'date'])
df = df.pivot(index = ['date', 'variable'], columns = 'location', values= 'value')
df.reset_index(inplace=True)
df.date = pd.to_datetime(df.date).dt.strftime('%d-%m-%Y')
df.loc[df['variable'] == 'daily_vaccinations', ['variable']] = "Vaccinazioni giornaliere"
df.loc[df['variable'] == 'daily_vaccinations_per_million', ['variable']] = "Vaccinazioni giornaliere ogni milione ab"
df.loc[df['variable'] == 'total_vaccinations', ['variable']] = "Totale vaccinazioni"
df.loc[df['variable'] == 'total_vaccinations_per_hundred', ['variable']] = "Totale vaccinazioni ogni cento abitanti"

df.to_csv("confronto_stati.csv")
df

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

location        date  ... United States
0         20-12-2020  ...           NaN
1         20-12-2020  ...           NaN
2         20-12-2020  ...     556208.00
3         20-12-2020  ...          0.17
4         21-12-2020  ...      57909.00
..               ...  ...           ...
71        06-01-2021  ...          1.60
72        07-01-2021  ...     378253.00
73        07-01-2021  ...       1143.00
74        07-01-2021  ...    5919418.00
75        07-01-2021  ...          1.79

[76 rows x 7 columns]

## Analisi vaccini Italia

In [ ]:
anagrafica = pd.read_csv("https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.csv")
dati_istat = pd.read_csv("https://raw.githubusercontent.com/vincnardelli/covstat/master/vaccini/dati_istat.csv", sep=";")
dati_istat

  fascia_anagrafica  pop_maschile  pop_femminile
0             20-29       3192324        2964859
1             30-39       3500589        3452131
2             40-49       4495422        4544377
3             50-59       4656253        4844927
4             60-69       3554434        3870741
5             70-79       2753864        3252966
6             80-89       1446283        2201193
7               90+        217463         577109

In [ ]:
anagrafica = anagrafica.merge(dati_istat, on="fascia_anagrafica")
anagrafica['Maschi'] = anagrafica['sesso_maschile']/anagrafica['pop_maschile']
anagrafica['Femmine'] = anagrafica['sesso_femminile']/anagrafica['pop_femminile']

In [ ]:
anagrafica_graph = anagrafica[['fascia_anagrafica','Maschi', 'Femmine']]
anagrafica_graph.set_index('fascia_anagrafica', inplace = True)
anagrafica_graph['Femmine'] = anagrafica_graph['Femmine']*-100
anagrafica_graph['Maschi'] = anagrafica_graph['Maschi']*100
anagrafica_graph = round(anagrafica_graph, 2)
anagrafica_graph.to_csv("italia_anagrafica.csv")
anagrafica_graph

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

                   Maschi  Femmine
fascia_anagrafica
20-29                0.45    -0.94
30-39                0.82    -1.23
40-49                0.67    -1.34
50-59                0.88    -1.59
60-69                1.03    -0.73
70-79                0.17    -0.09
80-89                0.19    -0.33
90+                  0.52    -1.17

## Regioni italiane

In [57]:
popolation_regions = np.array([ 1304970,      559084,        533050,   1947131,   5801692,         
                               4459477,        1215220,5879082, 1550640,    
                               10060574,  1525271,  305617,    4356406, 4029053, 1639591,  
                               4999891,  3729641,       541380,  882015,          125666, 4905854])
name_regions       = np.array(['Abruzzo','Basilicata','P.A. Bolzano','Calabria','Campania',
                               'Emilia-Romagna','Friuli Venezia Giulia','Lazio','Liguria',
                               'Lombardia','Marche','Molise','Piemonte','Puglia','Sardegna',
                               'Sicilia','Toscana','P.A. Trento','Umbria','Valle d\'Aosta','Veneto'])
area       = np.array(['ABR','BAS','PAB','CAL','CAM',
                               'EMR','FVG','LAZ','LIG',
                               'LOM','MAR','MOL','PIE','PUG','SAR',
                               'SIC','TOS','PAT','UMB','VDA','VEN'])

popolation = pd.DataFrame([name_regions, popolation_regions, area]).transpose()
popolation.columns = ['regione', 'popolazione', 'area']

In [69]:
regioni = pd.read_csv("https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-summary-latest.csv")
regioni[regioni['data_somministrazione'] == '2020-12-27']
regioni = regioni.merge(popolation, on='area')

regioni['Totale vaccinazioni ogni cento abitanti'] = regioni['totale']/regioni['popolazione']*100
regioni['Totale vaccinazioni ogni cento abitanti'] = round(regioni['Totale vaccinazioni ogni cento abitanti'].astype(float), 4)
regioni = regioni.rename(columns={'data_somministrazione': 'data', 
                        'totale': 'Totale vaccinazioni', 
                        'categoria_operatori_sanitari_sociosanitari': 'Operatori sanitari - sociosanitari', 
                        'categoria_personale_non_sanitario': 'Personale non sanitario', 
                        'categoria_ospiti_rsa': 'Ospiti RSA', 
                        'regione': 'Regione'})
regioni.reset_index(inplace=True)
regioni.data = pd.to_datetime(regioni.data).dt.strftime('%d-%m-%Y')
regioni.to_csv("regioni.csv")
regioni

     index        data  ... popolazione  Totale vaccinazioni ogni cento abitanti
0        0  27-12-2020  ...     1304970                                   0.0103
1        1  02-01-2021  ...     1304970                                   0.0421
2        2  03-01-2021  ...     1304970                                   0.0432
3        3  04-01-2021  ...     1304970                                   0.1081
4        4  05-01-2021  ...     1304970                                   0.1239
..     ...         ...  ...         ...                                      ...
248    248  06-01-2021  ...     4905854                                   0.1645
249    249  07-01-2021  ...     4905854                                   0.1630
250    250  08-01-2021  ...     4905854                                   0.1867
251    251  09-01-2021  ...     4905854                                   0.1557
252    252  10-01-2021  ...     4905854                                   0.0962

[253 rows x 12 columns]